### ISSUE TITLE
email to admin re new testimonial: formatting messed up

### ISSUE THREAD

**Issue by kaatvds** [massenergize/api#523]
The testimonial looks good on admin and on portal, but in the text in the email send to the admin, the html is showing:

![image](https://user-images.githubusercontent.com/30277868/169385776-410bbf9a-b38c-45a3-9300-8eaa6c404b0b.png)

**Comment by BradHN1** [comment]
Testing locally, using dev database, i don't see the testimonial body text:

![Image](https://user-images.githubusercontent.com/12800484/179790363-c27d2f6c-9818-4347-8f60-a65288f9b0e9.png)

where the body should be:
<p>This test has no rich text.</p>
<p>&nbsp;</p>

I don't think this is so bad since the cadmin needs to go to the admin portal anyway to approve it.
