### ISSUE TITLE
[Feature] Nudges - Weekly Report Email Nudge (Events)

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/api#586]
**User Story.**
As a cadmin or sadmin (Actor/User)
I want receive weekly emails containing an aggregation of events from all communities that were made live (and still live) since the last nudge. (Goal of the actor/user)
So that I can promote events in other communities in my community. (Why/What is the result)

**Additional details/context**
We already have some work for weekly report nudges that we'll build on. The frequency will change once other frequencies are added (daily, monthly, etc). Each admin in a community will receive weekly emails containing a list of all the events that were created on other communities since the last email. If there are no new events in other communities, admins should not receive an (empty) email.

This will be the first of a few scheduled tasks depending on admin's user preferences, so we can build off of this work for the other scheduled nudge tasks. Since these tasks will be added to down the road, this should be written with future nudge content in mind. Admins will be able to select how often they receive email updates once the other tasks are written. For this reason, this first nudge should not just send to all admins in a community. Instead we'll be querying from the DB to see who has their preference set to this scheduled task. (this will be everyone to start with). 

A weekly task should be run to query the DB to create the recipients list. Email content will be constructed from another query finding all the events that went live since the last weekly email report went out. We'll need to start tracking timestamps in the DB for when an event goes live to enable querying of this. The value in the DB entry should be cleared if the event becomes un-live. This will do the job of filtering out un-live events for free when we make our queries. 

The design of the email should account for future additions to the report these will include info about new users, actions, testimonials, vendors, and potentially a Google Analytics report/overview of the admin's own community. For now we can display a list of events including Event Title, Thumbnail, Date, Time, Location, the Community the event is from, and a button to copy the event to the user's own community. The copy button should not appear if the event is in the same community as the admin receiving the email. This is another reason to make emails by community and not send the same email to all admins.

We want to ship this with [issue 745](https://github.com/massenergize/frontend-admin/issues/745) so admins can click a link from this email report and essentially auto populate a new event form with all the same information from the event they're copying. This will allow admins to share events from other communities. We'll also aim to ship this with [issue 671](https://github.com/massenergize/frontend-admin/issues/671) so admins can browse live events from other communities and copy them from within the admin-portal.

**Acceptance criteria.**
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

**Comment by kaatvds** [comment]
When communities just get started, before going live, they sometimes create events and make them live - they won't show as the whole community isn't live. This is a small use case but is it easy to set the condition for an event to be shared in the nudge that the event AND the creating community are live?

**Comment by kaatvds** [comment]
Email template [DRAFT]

Dear MassEnergize Admin,

This is your weekly Event Sharing email.

Below are all the open events that have gone live on all the MassEnergize community sites since the previous email, last week.

If you want to promote any of these on your own site, all you have to do is click on the "copy event" link and you will be taken to the Admin interface, where you can then assign the event to your own community site, and make it live there. 

If the link doesn't go anywhere, that is because the event was taken offline (made not live), probably because it has already happened.

If you would rather not receive this events email, you can change your notification on the Admin site.

Onwards, together!

The MassE team

[in list, example of two events: order by name of PLACE of community, alphabetically]

- Wayland, September 24, 2022, 1- 3 PM, **EV petting zoo**,  in person. See it here [LINK to event on Enway site].  Copy event  here [LINK to admin site: copy of the event, if possible already assigned to admins community - not necessary]
- Wayland, October 12, 1 - 2 PM, I**nduction stove cooking,** webinar. See it here [LINK to event on Enway site].  Copy event  here [LINK to admin site]

**Comment by kaatvds** [comment]
wondering if it is possible for the email nudge to find if event is in person or online by checking if there is an address or not.

**Comment by Davidjwkinghorn** [comment]
> wondering if it is possible for the email nudge to find if event is in person or online by checking if there is an address or not.

We could do that by address provided or by seeing if a video conferencing link is provided.

**Comment by abdullai-t** [comment]
@kaatvds and @Davidjwkinghorn  I was thinking instead of adding two links, one for viewing the event details and the other for copying the event; why not one link saying (' See event details here [Link]) then on that page we can show a button to copy the event (button will only show if the viewing admin is not among the admins of the host community).
