### ISSUE TITLE
Users download: show summary of # actions done and todo rather than 10000 columns

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#633]
**User Story.**
As a cadmin or sadmin, I want to be able to see what actions a user has done.
But the users download (for sadmin) has hundreds of columns, one for every action defined on the platform.  We can't have this many columns, which is not a useful format.  

Instead, make the users download just summarize # actions done, # todo and carbon score]

From the Admin portal Users page, we should provide a dlownload for a given user that would include a list of the actions done and todo, with their communities and dates.

**Comment by apowelka** [comment]
@BradHN1 and others - is it possible to download a nested data set? The reason for the many, many columns are two-fold: a) we are moving from a 3D relational database to 2D, and b) that allowed us to see across another dimension which is across the communities.

I think we need a re-design of the data downloads and that community needs should be first.

Example: Action:  Curbside Composting. 

I am a community and I want to see who has done this action and who has marked it to-do. Maybe we change up the reporting so that we can download a report for each action?

I suggest a Cadmin go to that specific action on their portal and be able to download a report with: on title or face sheet: action name, carbon calculator name, carbon saved per action, total # done and # marked to-do. On a second sheet, we would have a list of user names with email addresses and in the second column be done or to-do.

To see what action is most popular or compare across actions, that is a separate download accessed from the home page. This time its rows that are the action names, followed by carbon calculator name, carbon saved per action, total # done and # marked to-do. Be great to add a hyperlink to the specific action report that then lists user names with emails addresses and done or to-do status.

**Comment by apowelka** [comment]
https://docs.google.com/document/d/10PK4u6DhlH-T0FI--703yWaZpVd5waWE_eLHWtTXtFE/edit SPECS
