### ISSUE TITLE
PROD - user event nudges not going out for JCAN community

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#891]
**Describe the bug**
User event nudges are enabled for JCAN, and JCAN has shared events recently but not posted any on their own.  Nudges to users do not appear to be going out.

**Comment by abdullai-t** [comment]
@BradHN1, I checked the events shared with or created by JCAN in production, and the last one was on 2023-07-11 at 11:00 pm, which is months back. The nudge only captures events whose start_date is within 7 days of when the nudge is generated.

<img width="1800" alt="Screenshot 2024-01-27 at 9 46 03 AM" src="https://github.com/massenergize/api/assets/42780120/1f942f2d-772b-4968-a1ec-18d47575aa65">

**Comment by BradHN1** [comment]
That list only shows the events JCAN is hosting.  They have shared events from other communities as recently as this past week.  
￼

**Comment by abdullai-t** [comment]
@BradHN1, it's possible that at the time the nudge was sent, the shared event was either not created or not published. Here is a screenshot I took today (01-02-2024) with the same filter as the screenshot above. I also checked the latest event ('Heat Pumps Are For Everyone'), and it turns out it was published on 28-01-2024, which was after the nudge was sent
<img width="1796" alt="Screenshot 2024-02-01 at 10 44 58 AM" src="https://github.com/massenergize/api/assets/42780120/41ecf6c8-6422-4a54-a37a-a30425d57587">
